.read data.sql

-- Q1
CREATE TABLE flight_costs as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';

-- Q2
CREATE TABLE schedule as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q3
CREATE TABLE shopping_cart as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q4
CREATE TABLE number_of_options as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q5
CREATE TABLE calories as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q6
CREATE TABLE healthiest_meats as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q7
CREATE TABLE average_prices as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q8
CREATE TABLE lowest_prices as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q9
CREATE TABLE shopping_list as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';


-- Q10
CREATE TABLE total_bandwidth as
  -- REPLACE THIS LINE
  SELECT 'YOUR CODE HERE';

